version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'SAE41'
      MYSQL_ROOT_PASSWORD: 'foo'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./app/SAE41.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      reseau_SAE41:
        ipv4_address: 192.168.1.10

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sae
    environment:
      PORT: 5000
    ports:
      - '5000:5000'
    restart: unless-stopped
    networks:
      reseau_SAE41:
        ipv4_address: 192.168.1.20

volumes:
  my-db:
  
networks:
  reseau_SAE41:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
        - gateway: 192.168.1.1
